name: Deploy Biddify to AWS

on:
  push:
    branches:
      - ChinhLV

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build .NET Razor App
      run: dotnet build ./Biddify/Biddify.csproj --configuration Release

    - name: Publish .NET app
      run: dotnet publish ./Biddify/Biddify.csproj -c Release -o ./publish

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1
      with:
        region: ap-southeast-1
        access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Build Docker image
      run: |
        docker build -t biddify-app ./Biddify
        docker tag biddify-app:latest ${{ secrets.ECR_REGISTRY }}/biddify-app:latest

    - name: Push Docker image to ECR
      run: |
        docker push ${{ secrets.ECR_REGISTRY }}/biddify-app:latest

    - name: Deploy to ECS
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ecs-task-def.json
        service: biddify-cluster-service
        cluster: biddify-cluster
        wait-for-service-stability: true
