name: Deploy Biddify to AWS

on:
  push:
    branches:
      - Developer

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ap-southeast-1

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install npm dependencies
      run: |
        cd ./Biddify
        npm install

    - name: Restore dependencies
      run: dotnet restore

    - name: Build .NET Razor App
      run: dotnet build ./Biddify/Biddify.csproj --configuration Release

    - name: Publish .NET app
      run: dotnet publish ./Biddify/Biddify.csproj -c Release -o ./publish

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build Docker image
      run: |
        docker build -t biddify-app -f ./Biddify/Dockerfile ./Biddify
        docker tag biddify-app:latest ${{ secrets.ECR_REGISTRY }}/biddify-app:latest

    - name: Push Docker image to ECR
      run: |
        docker push ${{ secrets.ECR_REGISTRY }}/biddify-app:latest

    - name: Deploy to ECS
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ecs-task-def.json
        service: biddify-cluster-service
        cluster: biddify-cluster
        wait-for-service-stability: true
